### ISSUE TITLE
Addition of  link to ESDC content

### ISSUE THREAD

**Issue by Syracopoulos** [gc-da11yn/gc-da11yn.github.io#580]
### Is your feature request related to a problem? Please describe.

Nope

### Describe the solution you'd like

Jeffrey referenced this [page](https://www.canada.ca/en/employment-social-development/programs/disability/arc/words-images.html) during a call and it is useful! He has confirmed that it is public domain, so we can link to it from the Resources page. It is a question we are often asked to answer.

### Who shall do the work?

- [ ] I will do it, I want to contribute
- [X] I am asking for someone else to please do the work

**Comment by JulieBB23** [comment]
@shawnthompson , just add the link to the [Additional Resources - Digital Accessibility Toolkit](https://a11y.canada.ca/en/additional-resources/)
and also on that page
[Designing accessible services](https://a11y.canada.ca/en/designing-accessible-services/)

**the title and the link should be**
A Way with Words and Images
**the description** :
Suggestions for the portrayal of people with disabilities. People with disabilities are asking Canadians, and the media in particular, to use respectful terms when writing and speaking about them or about issues that affect their lives. They are also asking that images chosen to portray them be respectful and not reinforce outdated stereotypes.

**Comment by Syracopoulos** [comment]
Unclassified | Non classifié

Thanks Julie!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by shawnthompson** [comment]
Here is the French version I will be using:

[Le pouvoir des mots et des images](https://www.canada.ca/fr/emploi-developpement-social/programmes/invalidite/cra/mots-images.html)
Suggestions pour la représentation des personnes en situation de handicap. Les personnes en situation de handicap demandent aux Canadiens, et aux médias en particulier, d'utiliser des termes respectueux lorsqu'ils écrivent et parlent d'elles ou des questions qui les concernent. Elles demandent également que les images choisies pour les représenter soient respectueuses et ne renforcent pas des stéréotypes dépassés.

Keep in mind the page we are linking to is using "personnes handicapées" instead of "personnes en situation de handicap".

**Comment by shawnthompson** [comment]
Ready for review

- https://deploy-preview-588--a11ycanada.netlify.appen/additional-resources/index.html#learning
- https://deploy-preview-588--a11ycanada.netlify.app/fr/ressources-additionnelles/index.html#apprentissage
- https://deploy-preview-588--a11ycanada.netlify.appen/designing-accessible-services/index.html
- https://deploy-preview-588--a11ycanada.netlify.app/fr/principes-de-conception-pour-des-services-accessibles/

**Comment by shawnthompson** [comment]
Will report language to ESDC's publishing team to correct.
