### ISSUE TITLE
[CHANGE] Typos in page title and date at bottom of page

### ISSUE THREAD

**Issue by lerouxa-btb** [gc-da11yn/gc-da11yn.github.io#599]
### What page is the change request for? Please supply the URI.

https://a11y.canada.ca/fr/rendre-vos-courriel-accessibles/index.html

### Approval needed?

None

### Who shall do the work?

- [ ] I will do it, I want to contribute
- [X] I am asking for someone else to please do the work

### Additional context

There is a spelling mistake in the title of this page. The word "courriel" should be plural, as in "Rendre vos courriels accessibles." Also, in French, there should be an unbreakable space before a colon, as well as a normal space after the colon. On the above-mentioned webpage, the date at the bottom of the page is missing the space after the colon. It's currently written "Date de modification :2024-02-09" but it should be " Date de modification : 2024-02-09."

**Comment by shawnthompson** [comment]
Thanks @lerouxa-btb for opening this issue. Sorry it took long to close something so simple.

We fixed the title, the date modified is a bigger issue which I opened a new issue (#615) for it and hopefully it will be fixed soon.

The new URL will be: https://a11y.canada.ca/fr/rendre-vos-courriels-accessibles/index.html for this page now because we create the URL based on the title of the page.

Thanks again for your help 😄
